import Head from 'next/head';

export default function TasksPage() {
	return (
		<div>
			<Head>
				<title>Tasks</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<TasksPage />
		</div>
	);
}
